---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: controller
    run_list:
      - recipe[deis::controller]
    attributes:
    data_bags_path: "test/integration/controller/data_bags"
